CREATE DATABASE IF NOT EXISTS stockbot
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE stockbot;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  telegram_id BIGINT NOT NULL UNIQUE,
  username VARCHAR(255) NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX ix_users_telegram_id (telegram_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stocks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(255) NULL,
  sector VARCHAR(255) NULL,
  market_cap BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX ix_stocks_code (code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stock_groups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stock_group_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stock_group_id INT NOT NULL,
  stock_code VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_group_stock (stock_group_id, stock_code),
  CONSTRAINT fk_group_items_group FOREIGN KEY (stock_group_id)
    REFERENCES stock_groups(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS analyses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  stock_code VARCHAR(20) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  raw_data JSON NOT NULL,
  structured_result JSON NULL,
  ai_result TEXT NOT NULL,
  final_signal VARCHAR(50) NULL,
  confidence_level VARCHAR(20) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_analyses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX ix_analyses_user (user_id),
  INDEX ix_analyses_stock (stock_code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS watchlists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  stock_code VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_watchlist_user_stock (user_id, stock_code),
  CONSTRAINT fk_watchlists_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS scan_results (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  group_name VARCHAR(100) NOT NULL,
  stock_code VARCHAR(20) NOT NULL,
  final_signal VARCHAR(50) NULL,
  confidence_level VARCHAR(20) NULL,
  summary TEXT NOT NULL,
  structured_result JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_scan_results_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX ix_scan_results_user (user_id),
  INDEX ix_scan_results_group (group_name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS scan_jobs (
  id VARCHAR(36) PRIMARY KEY,
  user_id INT NULL,
  group_name VARCHAR(100) NOT NULL,
  requested_limit INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'queued',
  total_stocks INT NOT NULL DEFAULT 0,
  processed_stocks INT NOT NULL DEFAULT 0,
  result JSON NULL,
  error_message TEXT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_scan_jobs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX ix_scan_jobs_user (user_id),
  INDEX ix_scan_jobs_group (group_name),
  INDEX ix_scan_jobs_status (status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS usage_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  event_type VARCHAR(30) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_usage_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX ix_usage_user_type_created (user_id, event_type, created_at)
) ENGINE=InnoDB;
